[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34"
winit = "0.29.15"
rand = "*"
num_cpus = "*"
once_cell = "*"
scoped_threadpool = "*"
